import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import LayoutShell from "@/components/layout-shell/LayoutShell";
import { AuthProvider } from "@/contexts/AuthContext";
import "../styles/globals.scss";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <AuthProvider>
          <LayoutShell children={children} />
        </AuthProvider>
      </body>
    </html>
  );
}
